name: routly
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/seifalmotaz/routly

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  parse_route:
  benchmarking: ^0.6.1
